# Generated by Django 4.2 on 2023-11-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0002_rename_plat0_orden_plato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='precio',
        ),
    ]
