# Generated by Django 4.2 on 2023-12-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orden', '0004_orden_estado_orden_preciototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='precioTotal',
            field=models.IntegerField(default=0),
        ),
    ]
