# Generated by Django 4.2 on 2023-11-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0002_alter_mesa_numeromesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='numeroMesa',
            new_name='cantCubiertos',
        ),
    ]
