# Generated by Django 4.2.4 on 2023-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0003_rename_numeromesa_mesa_cantcubiertos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
