# Generated by Django 4.2 on 2023-12-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mesa', '0004_mesa_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
